### ISSUE TITLE
MTD TotalSales

### ISSUE THREAD

**Issue by KMELNICH** [sql-bi/Bravo#333] opened 2022-04-18 16:09 UTC
### Describe the problem

These measures generate the same amounts
The 1st is the sum measure I created before introducing Bravo
The 2nd is the measure created by Bravo

1. TotalSales = SUM('Invoice Detail'[Sale Price])
2. MTD TotalSales = 
IF (
    [_ShowValueForDates],
    CALCULATE (
        [TotalSales],
        DATESMTD ( 'Date'[Date] )
    )
)

I added a DayofMonth column to the date table and filtered to <= DAY(TODAY) to get what I would expect. 

This is a very helpful tool for getting started and taking time intelligence to the next level, thank you! 

### Bravo version

0.9.8139.22766

### Tabular model

Power BI Dataset

### Power BI

Version: 2.104.702.0 64-bit (April 2022)

**Comment by KMELNICH** [comment] 2022-04-18 16:10
I added a DayofMonth column to the date table and filtered to <= DAY(TODAY) to get what I would expect. 

This is a very helpful tool for getting started and taking time intelligence to the next level, thank you!

**Comment by marcosqlbi** [comment] 2022-04-24 09:48
I do not understand whether you are reporting an issue or not.
If you are reporting an issue, please submit an example where we can reproduce the problem. The measures works as expected in our tests.

**Comment by marcosqlbi** [comment] 2022-06-08 07:40
Reviewing the issue, I understand that the goal was to get the month-to-today, which is not the month-to-date that uses the date selected in the report. I close the issue because it seems out of scope. Please reopen if there are additional considerations.

**Closed by marcosqlbi** 2022-06-08 07:40 UTC
Labels: bug, area-ManageDates
