### ISSUE TITLE
Converting DAX format to short line

### ISSUE THREAD

**Issue by CMB777** [sql-bi/Bravo#573] opened 2023-01-14 21:03 UTC
### Describe the problem

Error HTTP/500: Internal Server Error.
Response status code does not indicate success: 301 (Moved Permanently).

### Bravo version

1.0.1 (1.0.8381.30060)

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop

### Anything else ?

Trace Id: 00-1ef77a996efc035019b3299739fc9cf2-97c3b525c25b8294-00

**Comment by albertospelta** [comment] 2023-01-14 22:44
Duplicate of #574

**Closed by albertospelta** 2023-01-14 22:44 UTC
Labels: bug, untriaged
