### ISSUE TITLE
PBI Desktop - Error HTTP/500: Internal Server Error

### ISSUE THREAD

**Issue by mlongbsa** [sql-bi/Bravo#246] opened 2022-03-29 23:03 UTC
Bravo is unable to open a PBIX on desktop. Receive an internal server error message. 
---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-5b79c90ceeb88b4bb58e34f0ddb4e53a-211b843988072b43-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by danieleperilli** [comment] 2022-03-30 05:23
Thanks for reporting this. I'm closing this issue as a duplicate of #213.

**Closed by danieleperilli** 2022-03-30 05:23 UTC

**Comment by albertospelta** [comment] 2022-03-30 09:27
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
