### ISSUE TITLE
HTTP/500 Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ymessaoui15** [sql-bi/Bravo#234] opened 2022-03-29 11:18 UTC
Provide a detailed explanation of the issue in English.

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-b0d4cf0c3e0e9c489654c1ca1efc0e53-4e84a6782e512d4b-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by albertospelta** [comment] 2022-03-29 12:27
Thanks for reporting this. I'm closing this issue as duplicate of https://github.com/sql-bi/Bravo/issues/213

**Comment by albertospelta** [comment] 2022-03-29 12:27
Thanks for reporting this. I'm closing this issue as duplicate of https://github.com/sql-bi/Bravo/issues/213

**Closed by albertospelta** 2022-03-29 12:27 UTC
Labels: duplicate

**Comment by albertospelta** [comment] 2022-03-30 09:27
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
