### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ingecamhurtado** [sql-bi/Bravo#243] opened 2022-03-29 19:36 UTC
Provide a detailed explanation of the issue in English.

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-1b2bc76711d28d428addc5fd4010ccef-39b6757c96536240-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by danieleperilli** [comment] 2022-03-30 05:24
Thanks for reporting this. I'm closing this issue as a duplicate of #213.

**Closed by danieleperilli** 2022-03-30 05:24 UTC
