### ISSUE TITLE
DAX formatter service error HTTP/301

### ISSUE THREAD

**Issue by CMB777** [sql-bi/Bravo#574] opened 2023-01-14 21:17 UTC
### Describe the problem

Error HTTP/500: Internal Server Error.
Response status code does not indicate success: 301 (Moved Permanently).

### Bravo version

1.0.1 (1.0.8381.30060)

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop

### Additional context

Error HTTP/500: Internal Server Error.
Response status code does not indicate success: 301 (Moved Permanently).
Trace Id: 00-1ef77a996efc035019b3299739fc9cf2-97c3b525c25b8294-00
Version: 1.0.1 (1.0.8381.30060)

### Anything else ?

Trace Id: 00-1ef77a996efc035019b3299739fc9cf2-97c3b525c25b8294-00

**Comment by albertospelta** [comment] 2023-01-14 23:18
@CMB777 Thank you for reporting. 
It seems to be a problem with the daxformatter.com site which is the web service used by Bravo to format the DAX code.
I will share updates here as soon as we have more details.

**Comment by albertospelta** [comment] 2023-01-15 08:57
The issue was caused by the migration of an internal service that affected URL redirection - the problem is fixed now!

**Closed by albertospelta** 2023-01-15 08:57 UTC
Labels: area-FormatDax
