### ISSUE TITLE
Launch Error - Unauthorized Access Exception 

### ISSUE THREAD

**Issue by symplrTJB** [sql-bi/Bravo#475] opened 2022-08-30 19:20 UTC
```
System.UnauthorizedAccessException: Could not connect to the pipe because it was not owned by the current user.
   at System.IO.Pipes.NamedPipeClientStream.ValidateRemotePipeUser()
   at System.IO.Pipes.NamedPipeClientStream.TryConnect(Int32 timeout, CancellationToken cancellationToken)
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at Sqlbi.Bravo.Infrastructure.AppInstance.NotifyOwner() in D:\a\1\s\src\Infrastructure\AppInstance.cs:line 83
   at Sqlbi.Bravo.Program.Main() in D:\a\1\s\src\Program.cs:line 33
```

Program has been working great and launching fine until early last week? Has anyone seen this or no the steps needed to fix

**Comment by albertospelta** [comment] 2022-08-30 19:35
@symplrTJB What version and build of the application are you using and on what OS version ?

**Comment by symplrTJB** [comment] 2022-08-30 19:37
@albertospelta Bravo.0.9.5.x64 64 bit recommended version on Windows 10

**Comment by albertospelta** [comment] 2022-08-30 21:36
@symplrTJB Does the error occurs every time you run the applicaton ?
Can you share the output of this command ? `tasklist /V | findstr Bravo.exe`

**Comment by symplrTJB** [comment] 2022-08-31 13:11
C:\>TASKLIST /V | findstr Bravo.exe
Bravo.exe                    14860 Console                    1     26,020 K Not Responding                                              0:00:35 Bravo for Power BI - v0.9.5


And yes everytime - I have to right run as administrator to get the error to show up - otherwise normal clicking on app nothing happens.

**Comment by albertospelta** [comment] 2022-08-31 15:17
@symplrTJB when you right run as admin you are prompted to enter the username and password or just to confirm (yes/no button)?

I think this issue may be a duplicate of #459 - could you install this internal build and let me know if the issue still persists ?
https://bravorelease.blob.core.windows.net/bravo-internal/2022/08/25/20220825.1-0.9.8272.26313/Bravo.0.9.5.x64.msi

**Comment by symplrTJB** [comment] 2022-08-31 15:44
Just YES/No prompt - I'll try the later and respond back - thank you

**Comment by symplrTJB** [comment] 2022-09-01 13:01
Unfortunately still not launching - I'm wondering if my local IT changed something and is now causing the problem.

**Comment by symplrTJB** [comment] 2022-09-01 13:04
@albertospelta As I was typing out the previous comment it launched - thank you for the support and guidance.

**Comment by albertospelta** [comment] 2022-09-01 13:14
Duplicate of #459

**Closed by albertospelta** 2022-09-01 13:14 UTC
Labels: awaiting reply
