### ISSUE TITLE
Provide a meaningful issue title

### ISSUE THREAD

**Issue by Khazd0rf** [sql-bi/Bravo#229] opened 2022-03-29 10:02 UTC
Provide a detailed explanation of the issue in English.

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-1a726a606df7df4283ec589c8d72cd53-40ac487829984c45-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by Khazd0rf** [comment] 2022-03-29 10:02
Same error if I connect to an online data set or to powerbi desktop

**Comment by albertospelta** [comment] 2022-03-29 12:14
Thanks for reporting this. I'm going to close this issue as duplicate of #213

**Closed by albertospelta** 2022-03-29 12:14 UTC
Labels: duplicate

**Comment by albertospelta** [comment] 2022-03-30 09:26
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
