### ISSUE TITLE
Format DAX incorrectly states that a measure has an error

### ISSUE THREAD

**Issue by gdeckler** [sql-bi/Bravo#262] opened 2022-03-31 13:46 UTC
### Describe the problem

Attempting to format a measure fails stating that the measure has an error. However, the measure works fine and does not have an error.

### Bravo version

0.9.8124.15471

### Tabular model

Power BI Desktop, import mode

### Power BI

March 2022

### Steps to reproduce the behavior

1. Select the measure
2. Click the Format Selected button

### Additional context

This is the measure:

Battery = 
--Define the % to be colored in:
VAR percentageArea = .3

--Define the colors:
VAR fillColor = "#2eaf2e"
VAR backgroundColor = "#ffffff"

VAR Icon =
"data:image/svg+xml;utf8,
<svg xmlns='http://www.w3.org/2000/svg' height='245.19mm' width='79.022mm' version='1.1' viewBox='0 0 280.00001 868.77628'>

<defs>
    <clipPath id='maskClip'>
    <rect x='-500' y='"&810 - (percentageArea) * 360&"' width='100' height='"&(percentageArea)* 360&"'/>
    </clipPath>
</defs>

<g id='layer1' transform='translate(-194.29 -89.403)' fill=' "& backgroundColor &"'>
<g id='g4875' transform='matrix(2 0 0 2 1234.3 -746.54)' fill=' "& backgroundColor &"'>
<path id='rect4820' d='m-462.68 417.97c-5.54 0-10.225 4.4646-10 10v4.3882h-27.321c-11.08 0-20 8.92-20 20v380c0 11.08 8.92 20 20 20h100c11.08 0 20-8.92 20-20v-380c0-11.08-8.92-20-20-20h-27.321v-4.3882c0-5.54-4.46-10-10-10z' fill=' "& backgroundColor &"'/>
<g fill=' "& backgroundColor &"' >
<rect id='rect4810' height='360' width='100' y='452.36' x='-500' fill=' "& backgroundColor &"'/>
</g>
</g>
</g>

<g id='layer1' transform='translate(-194.29 -89.403)'>
<g id='g4875' transform='matrix(2 0 0 2 1234.3 -746.54)'>
<path id='rect4820' d='m-462.68 417.97c-5.54 0-10.225 4.4646-10 10v4.3882h-27.321c-11.08 0-20 8.92-20 20v380c0 11.08 8.92 20 20 20h100c11.08 0 20-8.92 20-20v-380c0-11.08-8.92-20-20-20h-27.321v-4.3882c0-5.54-4.46-10-10-10z'/>
<g style= 'fill:"&222222&"; clip-path:url(#maskClip1)'>
<g style= 'fill:"&fillColor&"; clip-path:url(#maskClip)'>
<rect id='rect4810' height='360' width='100' y='452.36' x='-500'/>
</g>
</g>
</g>
</g>
</svg>"
RETURN
Icon

**Comment by albertospelta** [comment] 2022-03-31 14:53
Thanks for reporting this! I'm closing this issue as a duplicate of https://github.com/sql-bi/Bravo/issues/217.

**Closed by albertospelta** 2022-03-31 14:53 UTC
Labels: duplicate

**Comment by marcosqlbi** [comment] 2022-04-11 21:09
This should be fixed now in DAX Formatter - because it depended on the service, there is no need to update Bravo.
Thanks for reporting it!
