### ISSUE TITLE
Disable Telemetry at Installation not working

### ISSUE THREAD

**Issue by daryl-lynch-bzy** [sql-bi/Bravo#283] opened 2022-04-05 11:03 UTC
### Describe the problem

Hi, During the installation of the Bravo BI tool (0.9.1 using msi), I deselected the Telemetry options.  However when I saw the "Diagnostics" option the Telemetry button was active.

### Bravo version

0.9.1

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop version March 2022

### Screenshots

![image](https://user-images.githubusercontent.com/76914701/161740265-7273dd65-27a0-41e5-a27f-4262276ef3ff.png)

**Comment by albertospelta** [comment] 2022-04-05 17:22
The option available during installation sets the default value to be used when starting the application for the first time - when the application has never been installed before. If telemetry is disabled during installation but subsequently re-enabled via the diagnostic options, then this latter setting wins and will be applied.

All application settings are stored in this JSON file `%LOCALAPPDATA%\Bravo\usersettings.json`. You can try closing the application and deleting (or renaming) this file. The next time you start the application you should find telemetry disabled, as you chose during installation.

**Comment by daryl-lynch-bzy** [comment] 2022-04-06 07:48
@albertospelta - "but subsequently re-enabled via the diagnostic options" - sorry are you suggesting that I changed the setting after the installation?  I am pretty sure I did not re-enable the

**Comment by albertospelta** [comment] 2022-04-06 08:12
@daryl-lynch-bzy,  thanks for your feedback! This could be a problem with the installer but unfortunately I cannot reproduce in my environment. Could you please provide the current values of these two settings?
- `telemetryEnabled` property in user settings file `%LOCALAPPDATA%\Bravo\usersettings.json` 
- `applicationTelemetryEnabled` key in registry `HKEY_LOCAL_MACHINE\SOFTWARE\SQLBI\Bravo\applicationTelemetryEnabled`

If you rename the `%LOCALAPPDATA%\Bravo\usersettings.json` file and start the application again, what is the value of the `telemetryEnabled` property in the newly created file?

Thank you!

**Comment by daryl-lynch-bzy** [comment] 2022-04-06 09:28
@albertospelta - It looks like the Reg is missing False value after the Install, so when the User opens Bravo for the first time, the setting forced by the App install is ignored.

**Comment by albertospelta** [comment] 2022-04-06 11:38
Thanks for reporting and for the detailed repro steps! I located the bug and the fix will be available with the next release.

**Closed** 2022-04-06 11:53 UTC
Labels: bug

**Comment by albertospelta** [comment] 2022-04-14 13:09
Fixed in [0.9.3](https://github.com/sql-bi/Bravo/releases/tag/v0.9.3)
