### ISSUE TITLE
Provide a meaningful issue title

### ISSUE THREAD

**Issue by jcharlton3** [sql-bi/Bravo#237] opened 2022-03-29 12:49 UTC
Provide a detailed explanation of the issue in English.

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-9ca23152b6d4204c9407977cad61f65d-6a8e6dbda0006e47-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by albertospelta** [comment] 2022-03-29 13:01
Thanks for reporting this. I'm closing this issue as duplicate of https://github.com/sql-bi/Bravo/issues/213

**Closed by albertospelta** 2022-03-29 13:01 UTC
Labels: duplicate

**Comment by albertospelta** [comment] 2022-03-30 09:28
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
