### ISSUE TITLE
Error 800 - No target tables found for attribute SQLBI_CallendarType

### ISSUE THREAD

**Issue by ZaphodBTH** [sql-bi/Bravo#607] opened 2023-02-24 17:07 UTC
### Describe the problem

I have a dataset with 2 SQL imports + 8 Excel imports. I used Bravo successfully to change the calendar date table for our Fiscal Year when I began the report building, now I need to change the First Day of Week and Bravo is throwing

Error 800: An exception occurred while executing the DAX template engine. No target tables found for attribute SQLBI_CallendarType=Fiscal.  

I have the data table still: Date = DateAutoTemplate

![image](https://user-images.githubusercontent.com/113474576/221241929-b6ef098d-189f-47f8-ae23-c657f27c3a5a.png)
![image](https://user-images.githubusercontent.com/113474576/221242017-91565826-0c89-4473-bf28-4ebf878bd8d6.png)
![image](https://user-images.githubusercontent.com/113474576/221242076-50956a32-260f-481a-86b3-f1bd33c0b727.png)

### Bravo version

1.0.1

### Tabular model

Power BI Desktop, import mode

### Power BI

Version: 2.114.864.0 64-bit (February 2023

**Comment by albertospelta** [comment] 2023-03-02 09:22
Hi @ZaphodBTH, thanks for reporting! I did some testing but I'm not able to reproduce this issue on my side. The problem may have been caused by metadata corruption of the Bravo template, but I can't tell what might be causing it.

Could you try to delete the `Date` and `DateAutoTemplate` tables from the PBIX report and try again to change the First Day of the Week?  **Before doing that, make sure to create a backup of your original PBIX file to avoid any data loss**

**Comment by albertospelta** [comment] 2023-03-19 09:47
I'm closing this issue as we have received this update via email.

> 02 Mar 2023 - Deleting the tables allowed Bravo to reupdate, error 800 has passed.

@ZaphodBTH feel free to reopen if the problem still exists, thanks.

**Closed by albertospelta** 2023-03-19 09:47 UTC
Labels: bug, area-ManageDates
