### ISSUE TITLE
Temporary 'hang' on first open of Format DAX tab.

### ISSUE THREAD

**Issue by mscottsewell** [sql-bi/Bravo#544] opened 2022-11-20 14:48 UTC
### Describe the problem

When I open the app the first time and choose the 'Format DAX' tab, it appears to 'hang' briefly - the 'spinny' refresh icon is not moving and is still has the button for 'analyze now' showing, but you can't interact with the app at all. - After a brief delay (20-30 Seconds) the control returns to the user. - 
The request is to 1) either avoid the wait, or 2) if it's needed, just alert the user that you'll give them control in a moment.

![Screenshot_20221120_084109](https://user-images.githubusercontent.com/6276300/202908645-ce49ed57-ef86-4193-a8b8-10a337ee4a6b.png)

### Bravo version

1.0.0 (1.0.8339.28087)

### Tabular model

Power BI Desktop, import mode

### Power BI

Version: 2.110.1085.0 64-bit (October 2022)

**Comment by albertospelta** [comment] 2022-11-21 08:02
Hi @mscottsewell, unfortunately I can't reproduce the issue. Does the hang happen only with online datasets or also with a local PBIX? Does it happen at every Bravo startup or only at the first startup after installing a new version?

**Comment by mscottsewell** [comment] 2022-11-21 14:05
It's a local PBIX - and it only happens during every startup of bravo - and only on the formatting tab. - It happened with the released version and the beta I just downloaded. 

My last measurement was that it lasted about 22 seconds - but about 50 seconds if I click around aggressively during the 'hang' time.   _This is **not** a showstopper for me_. 

This is the view from task manager during that brief period after I first open (but haven't yet clicked on anything on) the formatting tab. Not sure if this is helpful to you, but it does show some process running pretty hard just after opening the formatting tab for the first time.
![image](https://user-images.githubusercontent.com/6276300/203073280-ff967526-9e16-42cc-9802-c737561efee7.png)

**Comment by albertospelta** [comment] 2022-11-22 14:03
@mscottsewell Is it possible for you to share a minimal .pbix file that reproduces this behavior?

**Comment by mscottsewell** [comment] 2022-11-22 15:50
@albertospelta  - Here's a PBIX - this contains ONLY demo data - no real customer information.
[Link to demo file on GitHub](https://github.com/mscottsewell/Power-BI-D365-Sales/blob/main/SQLBI-TEMP/Contoso%20Sales.pbix)

**Comment by mscottsewell** [comment] 2022-11-22 16:47
@albertospelta  - Oddly enough, when I turned 'on' diagnostics, I didn't see the pause. - when I turned 'off' diagnostics and re-started, it returned. 🤷‍♂️

**Comment by albertospelta** [comment] 2022-11-22 17:01
@mscottsewell thank you very much, this is a very useful detail! 
I can now reproduce the error every time I start the application **only when the diagnostics is turned off**

**Comment by albertospelta** [comment] 2022-11-23 13:11
@mscottsewell We have just pushed a fix for this issue, if you want to test you can try the latest internal `Dev` build `1.0.8362.21973`

**Comment by mscottsewell** [comment] 2022-11-23 13:21
Yes! - Just re-tested with 1.0.0-internal-20221123.1-main-b7152407794543856b42adc4c523480f3b25e564 (1.0.8362.21973) and it worked great! - Thank you!

**Closed** 2022-11-23 13:24 UTC
Labels: bug

**Comment by albertospelta** [comment] 2022-12-12 17:23
Fixed in version [1.0.1](https://github.com/sql-bi/Bravo/releases/tag/v1.0.1)
