### ISSUE TITLE
Error 200: The Power BI Desktop Analysis Services instance does not contain any databases

### ISSUE THREAD

**Issue by smirya** [sql-bi/Bravo#235] opened 2022-03-29 11:20 UTC
The report I tried to open is connected "Live" to Power BI Dataset (connected "Live" to Tabular Model AS DB)
---
Error 200: The Power BI Desktop Analysis Services instance does not contain any databases. Try to connect to the report using the Bravo icon in the External Tools of Power BI Desktop.
Version: 0.9.0 (0.9.8121.26944)

**Comment by danieleperilli** [comment] 2022-03-29 13:32
Thanks for reporting this. I'm closing this issue as a duplicate of #216

**Comment by albertospelta** [comment] 2022-03-29 14:39
Hi @smirya,

Did you tried to connect to the external dataset using the Bravo connection option "_Connect To Power BI Service_"? This is the connection option to be used when the PBIX report is "live-connected" to an external Power BI Dataset. 

If you prefer, you can also connect to the report using the Bravo icon in the External Tools ribbon of Power BI Desktop.

**Comment by smirya** [comment] 2022-03-29 15:19
> Hi @smirya,
> 
> Did you tried to connect to the external dataset using the Bravo connection option "_Connect To Power BI Service_"? This is the connection option to be used when the PBIX report is "live-connected" to an external Power BI Dataset.
> 
> If you prefer, you can also connect to the report using the Bravo icon in the External Tools ribbon of Power BI Desktop.

Yes, I tried both: 
![image](https://user-images.githubusercontent.com/32505476/160645486-8541f655-b255-422e-8fac-9523401abd99.png)
![image](https://user-images.githubusercontent.com/32505476/160645828-50a9d587-3d1a-48b4-a925-51ff3fd4cd37.png)

**Closed** 2022-04-05 12:19 UTC
Labels: bug

**Comment by albertospelta** [comment] 2022-04-05 16:31
This should be fixed with version [0.9.2](https://github.com/sql-bi/Bravo/releases/tag/v0.9.2), feel free to reopen if the issue still exists.
