### ISSUE TITLE
HTTP/500: Internal Server Error

### ISSUE THREAD

**Issue by monzerosama** [sql-bi/Bravo#251] opened 2022-03-30 06:36 UTC
Hello,
This is the 1st usage of Bravo, just open it, and I got the below Error,
I'm running the latest Power BI version on Win 11.

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-6c1322a424e0274ba2b05497b5053adf-a3269b7bb931ee4c-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by danieleperilli** [comment] 2022-03-30 06:40
Thanks for reporting this. I'm closing this issue as a duplicate of #213.

**Closed by danieleperilli** 2022-03-30 06:40 UTC

**Comment by albertospelta** [comment] 2022-03-30 09:25
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
