### ISSUE TITLE
Error HTTP/500: Internal Server Error.

### ISSUE THREAD

**Issue by BiswajeetBCG** [sql-bi/Bravo#233] opened 2022-03-29 11:10 UTC
Provide a detailed explanation of the issue in English.

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-e01b747aac27704f9416f181691906a6-acba04c6028f6e4c-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by albertospelta** [comment] 2022-03-29 12:16
Thanks for reporting this. I'm closing this issue as duplicate of https://github.com/sql-bi/Bravo/issues/213

**Closed by albertospelta** 2022-03-29 12:16 UTC
Labels: duplicate

**Comment by albertospelta** [comment] 2022-03-30 09:26
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
