### ISSUE TITLE
Error HTTP/500: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by PratimaBelel** [sql-bi/Bravo#250] opened 2022-03-30 05:00 UTC
Provide a detailed explanation of the issue in English.

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-21e432f295a41c4f84cd2e2a884dbebb-5a19b138b2221b41-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by danieleperilli** [comment] 2022-03-30 05:26
Thanks for reporting this. I'm closing this issue as a duplicate of #213.

**Closed by danieleperilli** 2022-03-30 05:26 UTC

**Comment by albertospelta** [comment] 2022-03-30 09:25
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
