### ISSUE TITLE
DAX format for calculated tables

### ISSUE THREAD

**Issue by emirtut** [sql-bi/Bravo#352] opened 2022-04-22 02:34 UTC
### The feature request

BRAVO is currenty support DAX format for measures only.

### Proposed solution

New features for DAX format should include analysis for tables (created with DAX) beside measures.
After analysis user should have option to choose DAX format for tables, not just measures only.

**Comment by marcosqlbi** [comment] 2022-04-24 09:44
We will consider adding DAX Formatter for calculated columns and calculated tables in a future version of Bravo.
It is not in scope for 1.0.

**Comment by marcosqlbi** [comment] 2022-04-24 10:35
Closing as a duplicate of #222 - please follow that issue for updates.

**Closed by marcosqlbi** 2022-04-24 10:35 UTC
Labels: enhancement
