### ISSUE TITLE
Can't find Open Power BI Desktop files

### ISSUE THREAD

**Issue by aidarwin** [sql-bi/Bravo#676] opened 2023-06-06 11:17 UTC
### Describe the problem

Hi guys, Bravo doesn't want to pickup my local PBIX file. I have turned off Auto Time Intelligence in the Current File Data Load section. If i create a new report (Untitled) without touching this setting I am able to open the report in Bravo but it won't let me manage dates. If i use the Browse feature of Bravo and try to open the Power BI Desktop file, the report opens in Power BI but bravo still waits indefinitely.  If i open the Power BI Desktop file it says "No unopened reports available".

### Bravo version

1.0.2 (1.0.8480.21768)

### Tabular model

Power BI Desktop, import mode

### Power BI

2.117.984.0 64-bit (May 2023)

### Steps to reproduce the behavior

--No .PBIX File opened
1. Open Bravo
2. Go to Attach to Power BI Desktop
3. Click Browse
4. Local Power BI Desktop .pbix file that has Auto Time Intelligence turned off in Option for Current Load settings.
5. Waiting for File Opening in Power BI Desktop indefinitely (Power BI Desktop report opens)

--Existing .PBIX File opened
1. Open Local Power BI Desktop .pbix file that has Auto Time Intelligence turned off in Option for Current Load settings.
2. Wait for Power BI Desktop to open .pbix file
3. Open Bravo
4. Go to Attach to Power BI Desktop
5. Local Power BI Desktop .pbix file is already opened (that has Auto Time Intelligence turned off in Option for Current Load settings.)
6. Nothing is listed in the "Active Report in Power BI Desktop" list

### Screenshots

<img width="1226" alt="SQLBI Bravo Screenshot" src="https://github.com/sql-bi/Bravo/assets/103006306/c466edc7-23d2-4031-8a1b-97c1c95f0b19">

**Comment by albertospelta** [comment] 2023-06-06 14:47
Ho @aidarwin, I think the issue is caused by the same bug that was recently reported here https://github.com/sql-bi/Bravo/issues/671#issuecomment-1571642807 Did you enable the "Save to OneDrive/SharePoint" preview feature in Power BI Desktop? 

![image](https://github.com/sql-bi/Bravo/assets/1957788/fdd7bfda-ea89-4fff-b1c8-4430e4b75662)

**Comment by albertospelta** [comment] 2023-06-15 09:13
I'm closing this issue as this bug was fixed in version [1.0.3](https://github.com/sql-bi/Bravo/releases/tag/v1.0.3), but feel free to reopen if the problem persists. Thank you!

**Closed by albertospelta** 2023-06-15 09:13 UTC
Labels: bug, awaiting reply

**Comment by aidarwin** [comment] 2023-06-15 09:24
Yeah good I tested in the Dev version and it worked
