### ISSUE TITLE
Error 200: Power BI process not yet ready

### ISSUE THREAD

**Issue by digoms44** [sql-bi/Bravo#415] opened 2022-05-19 11:41 UTC
### Describe the problem

Error 200: Power BI Desktop process is opening or the Analysis Services instance is not yet ready.

### Bravo version

0.9.4 (0.9.8158.22794)

### Tabular model

Power BI Desktop, import mode

### Power BI

january/22

**Comment by albertospelta** [comment] 2022-05-19 14:43
@digoms44 This message is shown when Bravo cannot connect to Power BI Desktop because the underlying process and database are not yet fully initialized (they are still starting up). 
Is your PBIX file using a local model or is it connected to an online PBI dataset ?
Can you provide a sample PBIX file and/or the steps to reproduce ?

**Comment by albertospelta** [comment] 2022-09-09 12:16
Closing as a duplicate of https://github.com/sql-bi/Bravo/issues/476 - please follow that issue for updates.

**Closed by albertospelta** 2022-09-09 12:16 UTC
Labels: bug, awaiting reply
