### ISSUE TITLE
Format Dax 407 proxy issue

### ISSUE THREAD

**Issue by Chris-Burgess-ACTGOV** [sql-bi/Bravo#494] opened 2022-10-07 00:03 UTC
### Describe the problem

Error HTTP/500: Internal Server Error.
The proxy tunnel request to proxy 'http://proxy.xxxx.gov.au:9090/' failed with status code '407'."

### Bravo version

0.9.6 (0.9.8291.23631)

### Tabular model

Power BI Desktop, import mode

### Power BI

Version: 2.108.825.0 64-bit (August 2022)

### Steps to reproduce the behavior

Format Dax
spins and nothing returned
Format Selected produces 407 err

### Anything else ?

Trace Id: 00-51728543fa5419b92aa709925c2245e7-8c5b1eebdae99016-00

**Comment by albertospelta** [comment] 2022-10-07 08:33
@Chris-Burgess-ACTGOV Are you working from behind a proxy server? 
In that case, please configure the proxy credential settings under Options > Proxy.

More details on the configuration are available here:
https://docs.sqlbi.com/bravo/configuration/options#proxy

![image](https://user-images.githubusercontent.com/1957788/194509225-07fb9d17-e0ce-4661-b9d3-6af5663e0a5b.png)

**Comment by Chris-Burgess-ACTGOV** [comment] 2022-10-09 06:56
Hi Alberto
Working at a Government Agency. 
Firewall, AppLocker in place and cannot configure the proxy.

I will need to raise an internal ticket to get Bravo allowed I think.
 
FYI had some colleagues install the the Self Contained User & portable versions and they get AppLocker’d when launching.
 
So two issues really emerging:
Proxy permissions required for self contained
Applocker rules required for user/portable
Nothing you guys can do in the product development to address these?
 
Cheers
 
Chris

**Comment by albertospelta** [comment] 2022-10-09 10:40
> FYI had some colleagues install the the Self Contained User & portable versions and they get AppLocker’d when launching.

I think your organization's AppLocker rules allow users to run executable files only from the `Program Files` folder. At the application level we cannot bypass these security rules, per-user and portable versions must be explicitly authorized by your organization.

Regarding proxy permissions, I think Bravo is not allowed to connect to the DaxFormatter web service, probably because the URL address must be authorized. The URL addresses that must be authorized to allow Bravo to access the DaxFormatter service are https://www.daxformatter.com and https://daxformatter.azurewebsites.net

Could you open this URL address and share here what the browser shows ?
https://www.daxformatter.com/api/daxformatter/daxtextformat

The output should look like this:
![image](https://user-images.githubusercontent.com/1957788/194751946-597f5e86-7f1a-4fe9-8045-4896b438fb65.png)

**Comment by Chris-Burgess-ACTGOV** [comment] 2022-10-09 23:42
Hey Alberto
**{"formatted":"","errors":[]}** is what i see (both using Direct Access and from behind firewall)
Can also access the DaxFormatter URLs direct from Edge without issue, but not through Bravo.
Bravo launched via external tools or launched direct exhibit same error.

Cheers

Chris

**Comment by albertospelta** [comment] 2022-10-10 09:21
What is your current proxy configuration in Bravo ?

![image](https://user-images.githubusercontent.com/1957788/194832705-f5a8e93f-3f51-4d0b-92d8-65efcde27e2f.png)

If you open the Options\About panel in Bravo a check for available updates is performed. 
At the end of the update check what message is displayed? "Bravo is up to date" or an error message like the one below?

![image](https://user-images.githubusercontent.com/1957788/194833889-b267303e-6990-4895-b96e-b538f5b1ecaa.png)

If possible, it would be helpful to ask the organization's IT support which proxy configuration should be used.

**Comment by Chris-Burgess-ACTGOV** [comment] 2022-10-10 10:14
Proxy setting is 'System'
'Bravo is up date' (0.9.6 (0.9.8291.23631)
Have tried running Bravo elevated (using same a/c as installed) - same issue.

Will see if i can get proxy configs and get 'temporary' line of sight. 
Ultimately I think will need to go down packaging route to industrialise.

**Comment by Chris-Burgess-ACTGOV** [comment] 2022-10-11 07:26
Hi Alberto
Working at a Government Agency.
Firewall, AppLocker in place and cannot configure the proxy.

I will need to raise an internal ticket to get Bravo allowed I think.

FYI had some colleagues install the the Self Contained User & portable versions and they get AppLocker'd when launching.

So two issues really emerging:

  *   Proxy permissions required for self contained
  *   Applocker rules required for user/portable
Nothing you guys can do in the product development to address these?

Cheers

Chris

Chris Burgess | Power BI Data Engineer | 0403472887

***@***.***

**Comment by albertospelta** [comment] 2022-10-11 09:08
Hi @Chris-Burgess-ACTGOV, to better understand what the cause of the proxy authentication problem is, we made changes and released an internal test build, it would be great if you could test it and let us know if the proxy issue still persists.

You can download this new build using the link below or switch from `Stable` to `Dev` in the Bravo Option\About panel and follow the download link.
https://bravorelease.blob.core.windows.net/bravo-internal/2022/10/10/20221010.3-0.9.8318.30701/Bravo.0.9.6.x64.msi

**Comment by Chris-Burgess-ACTGOV** [comment] 2022-10-11 22:21
Hey @albertospelta 
Have Installed Dev Version

<img width="537" alt="image" src="https://user-images.githubusercontent.com/60373199/195208063-be102f10-b7bf-4474-b7bd-9b504bbebbd2.png">

Error HTTP/500: Internal Server Error.
The proxy tunnel request to proxy 'http://proxy.act.gov.au:9090/' failed with status code '407'."
Trace Id: 00-508e799a2415ab38ee97c818ef40c1a6-4fd9391684d4ae33-00
Version: 0.9.6-internal-20221010.3-0.9.8318.30701-main-61dbe1f97375767483502ab358bd4fd8d825cd54 (0.9.8318.30701)

407 remains
I checked for both active reports and datasets on powerbi.com in case cloud/on prem was a factor (Knowing it isnt)

**Comment by albertospelta** [comment] 2022-10-12 08:01
@Chris-Burgess-ACTGOV Thanks for testing it out! Unfortunately, it doesn't seem to have solved the proxy issue. 

Bravo uses the same proxy configuration for all HTTP requests, it can access the Internet (e.g. update check, datasets on  powerbi.com), except for the URL address of the DaxFormatter web service, for which the proxy authentication is required. I think it would be useful to ask IT guys to check why only for DaxFormatter HTTP requests we have this behavior.

Regarding the AppLocker rules required for user/portable version, I think there is nothing we can do in the product development. Both Bravo MSI installer and the Bravo executable are digitally signed and an AppLocker publisher rule condition could be applied in order to avoid the app to get AppLocker'd when launching.

![image](https://user-images.githubusercontent.com/1957788/195284980-1203cff9-0dd9-4a9a-8466-c8a240810ea4.png)

**Comment by Chris-Burgess-ACTGOV** [comment] 2022-10-13 02:08
Hey @albertospelta I have a solution.
Proxy - custom - http://proxy.xxx.yyy.au:9090 - 9090 explicitly required.

Additionally
For connections to powerbi.com datasets also require - Tenant settings
<img width="705" alt="image" src="https://user-images.githubusercontent.com/60373199/195481764-fcb68d9e-34e2-4650-8bb4-ad407ef7ca5b.png">

<img width="442" alt="image" src="https://user-images.githubusercontent.com/60373199/195481556-56ad505d-e741-4c3a-9559-1e04324ef974.png">

Found a capacity that was set to read, changed to read write and we hit paydirt for all capacities in the Tenancy.

AppLocker will be addressed as part of the approval & packaging process.

Great tool and great work from you guys.

Happy of Australia :)

**Comment by Chris-Burgess-ACTGOV** [comment] 2022-10-13 04:31
@albertospelta One further...

`Error 10: A connection problem arises between the server and Bravo.
The specified Power BI workspace is not found.

Technical Details:
RootActivityId: 75f75078-9984-42f6-a6b0-4e16014a7433
Trace Id: 00-10a82270feac38b0b634054e0475f894-9106091162b6ddf0-00
Version: 0.9.6 (0.9.8291.23631)`

Got this when trying to connect to a workspace dataset that has a "\" **within** the workspace name. Slash at end is ok, but within no chocolates. Prob a low user case but WS names are free text really!!??
 I guess your not using the workspace id to pass request thru?
 (Let me know if want to raise as sep issue?)
 
 Cheers
 
 Chris

**Comment by albertospelta** [comment] 2022-10-13 07:31
```
I have a solution. 
Proxy - custom - http://proxy.xxx.yyy.au:9090/ - 9090 explicitly required.
```
@Chris-Burgess-ACTGOV great! 
I am closing this issue, but feel free to reopen in case of further issues/questions. Thanks!

I just created this new issue here https://github.com/sql-bi/Bravo/issues/500 to track this error.

**Closed by albertospelta** 2022-10-13 07:31 UTC
Labels: bug, awaiting reply
