### ISSUE TITLE
Lost connection to PBI report

### ISSUE THREAD

**Issue by Terpsixore** [sql-bi/Bravo#510] opened 2022-10-29 20:45 UTC
### Describe the problem

When opening Bravo within PowerBI it seems to somehow lose contact with my Power BI report in Power BI desktop after a few seconds. It's there for a moment though. On the NOT AVAILABLE button in Bravo the message says "The report was closed i Power BI desktop. Any writing operation is disallowed". But the report is not closed in PBI desktop. Nor can i connect to a pbix file on my computer, but works to connect to resport i PBI service.
What can this be about?  I'm running the latest version of PBI desktop, Pro user license. Swedish. I've tried restart and reinstallion of both Bravo and PBI desktop.

### Bravo version

0.9.6 (0.9.8291.23631)

### Tabular model

Power BI Desktop, import mode

### Power BI

PBI desktop Version: 2.110.805.0 64-bit (october 2022)

### Steps to reproduce the behavior

Open PBI desktop
Open pbix file with two dataset and one visualisation
            No date table generated
            No existing data table
Go to External tools
Open Bravo
Reads report 
Lose connection to report after a few seconds

### Screenshots

![image](https://user-images.githubusercontent.com/75843490/198851316-b17ea034-f172-46d1-b54c-76d194c1d02b.png)
![image](https://user-images.githubusercontent.com/75843490/198851323-50b6089e-bfc2-441b-a677-619143074367.png)

**Comment by albertospelta** [comment] 2022-10-30 08:48
@Terpsixore thanks for reporting! This is a bug similar to the one already reported here https://github.com/sql-bi/Bravo/issues/476#issuecomment-1236915152

This issue is due to a different text format that Power BI Desktop applies to the report name/title depending on the display culture used on the PC. Bravo uses this title to get the report name and this small difference in format is the cause of the "NOT AVAILABLE" message.

Swedish:
![Screenshot 2022-10-30 082654](https://user-images.githubusercontent.com/1957788/198868665-f8997fef-e61e-48d6-831e-c6086f14d4e1.png)

English:
![image](https://user-images.githubusercontent.com/1957788/198868704-034f9d24-7a92-4f07-8ceb-bed54a81967e.png)

I have just pushed a fix for this issue, if you want to test you can try the internal build. To upgrade Bravo to this version (`0.9.8338.15099`) you can change the update channel from `Stable` to `Dev` in the options panel as shown in the following image. 

![image](https://user-images.githubusercontent.com/1957788/198869439-103ff8db-7608-4c6f-8086-5296e0065e3b.png)

**Comment by Terpsixore** [comment] 2022-10-30 20:55
Many many thanks, works great now!

**Closed** 2022-10-30 21:00 UTC
Labels: bug

**Comment by albertospelta** [comment] 2022-11-02 09:03
Fixed in version [1.0.0](https://github.com/sql-bi/Bravo/releases/tag/v1.0.0)
