### ISSUE TITLE
Unable to connect with PBI desktop

### ISSUE THREAD

**Issue by Paruccone** [sql-bi/Bravo#226] opened 2022-03-29 09:54 UTC
Ciao amici!

I just tried to open a file in PBI (using may 2021 RS) and to launch Bravo. Same outcome if I run Bravo as Admin.

Any idea what else I could try? Or any other info I can gather on the cause? Thx!

This happens with one specific file. Tried another one and Bravo connects to PBI flawlessly so I'd exclude system's issues.
---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-11dae798584777448d53d6285ab20c69-bad9c14d8275564d-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by albertospelta** [comment] 2022-03-29 13:37
Thanks for the report, we are aware of this. I am closing this issue as a duplicate of #213

**Closed by albertospelta** 2022-03-29 13:37 UTC
Labels: bug

**Comment by albertospelta** [comment] 2022-03-30 09:28
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
