### ISSUE TITLE
HTTP/500 Error when opening Active Report on Power BI

### ISSUE THREAD

**Issue by joe-smith-powerbi** [sql-bi/Bravo#297] opened 2022-04-07 17:08 UTC
Provide a detailed explanation of the issue in English.

Opened Bravo after installing. Selected Open, then my Active Report in Power BI. Received HTTP/500 error. 
PBIX is for large (> 2GB) dataset and report, with no known issues.

---
Error HTTP/500: Internal Server Error.
Object reference not set to an instance of an object.
Trace Id: 00-7a07bf0fc937dc45ace3d99cead7d24b-9a8eb0aa182d0d41-00
Version: 0.9.0 (0.9.8121.26944)

**Comment by albertospelta** [comment] 2022-04-07 17:31
Duplicate of #213 

Hi @joe-smith-powerbi, thanks for reporting! This issue has already been fixed, you can take the latest version [0.9.2 here](https://github.com/sql-bi/Bravo/releases/tag/v0.9.2).

**Comment by joe-smith-powerbi** [comment] 2022-04-07 18:09
thanks @albertospelta! I was unaware of the update; https://www.sqlbi.com/tools/bravo-for-power-bi/ still lists the latest as v0.9.0, so I assumed it was up-to-date; I also received no notification of a newer version when I opened Bravo. I have since updated, and verified issue is resolved.

**Comment by albertospelta** [comment] 2022-04-08 14:29
HI @joe-smith-powerbi, I'm reopening this issue just to check that the update notification works correctly after updating to the latest version. Can you please test if you receive an update notification after changing the update channel from "Stable" to "Dev"? Restarting the application should also show a notification in Windows Action Center - right of the taskbar.
Thanks!

![image](https://user-images.githubusercontent.com/1957788/162456299-de152291-067b-4a98-8392-c1d68df87164.png)

**Comment by joe-smith-powerbi** [comment] 2022-04-08 14:50
HI @albertospelta, thanks for looking into it more! Test results:
- Verified: dev channel shows new version update as above screenshot
  - changelog link redirects as expected 
  - did not test download link
- Verified: switch to dev channel, close app, open app; received WAC notification: 
![image](https://user-images.githubusercontent.com/103209268/162458992-b163801d-0cc6-46b4-b175-70a5fa5e7913.png)
  - Verified receiving in-app update notification: 
![image](https://user-images.githubusercontent.com/103209268/162460063-6ac15aa3-87ae-4c3f-83f7-8317720c36d6.png)
  - Note, this notification appears after switching channel, then app restart. While this is _my_ expectation, a literal interpretation of your test could indicate you expect it directly after switching channel, which it does not.

**Comment by albertospelta** [comment] 2022-04-08 15:35
This is the proper behaviour
> notification appears after switching channel, then app restart

Thanks @joe-smith-powerbi !

**Closed by albertospelta** 2022-04-08 15:35 UTC
Labels: duplicate
