### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'Photino.Native' or one of its dependencies

### ISSUE THREAD

**Issue by Anaa97** [sql-bi/Bravo#231] opened 2022-03-29 10:21 UTC
### Describe the problem

Hello!

I get this error when I try to open Bravo BI.

System.DllNotFoundException: Unable to load DLL 'Photino.Native' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at PhotinoNET.PhotinoWindow.Photino_register_win32(IntPtr hInstance)
   at PhotinoNET.PhotinoWindow.<>c.<.ctor>b__238_0()
   at PhotinoNET.PhotinoWindow.Invoke(Action workItem)
   at PhotinoNET.PhotinoWindow..ctor(PhotinoWindow parent)
   at Sqlbi.Bravo.Infrastructure.AppWindow.CreateWindow() in D:\a\1\s\src\Infrastructure\AppWindow.cs:line 58
   at Sqlbi.Bravo.Infrastructure.AppWindow..ctor(IHost host, AppInstance instance) in D:\a\1\s\src\Infrastructure\AppWindow.cs:line 35
   at Sqlbi.Bravo.Program.Main() in D:\a\1\s\src\Program.cs:line 25

How can I fix this error ?

Please help ~~!
Thank you!

### Bravo version

na

### Tabular model

Power BI Desktop, import mode

### Power BI

Power BI Desktop version March 2022

### Steps to reproduce the behavior

1. Install Bravo BI
2. Open PowerBI Desktop
3. Access External Tools
4. Click on Bravo BI
5. Error:
System.DllNotFoundException: Unable to load DLL 'Photino.Native' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at PhotinoNET.PhotinoWindow.Photino_register_win32(IntPtr hInstance)
   at PhotinoNET.PhotinoWindow.<>c.<.ctor>b__238_0()
   at PhotinoNET.PhotinoWindow.Invoke(Action workItem)
   at PhotinoNET.PhotinoWindow..ctor(PhotinoWindow parent)
   at Sqlbi.Bravo.Infrastructure.AppWindow.CreateWindow() in D:\a\1\s\src\Infrastructure\AppWindow.cs:line 58
   at Sqlbi.Bravo.Infrastructure.AppWindow..ctor(IHost host, AppInstance instance) in D:\a\1\s\src\Infrastructure\AppWindow.cs:line 35
   at Sqlbi.Bravo.Program.Main() in D:\a\1\s\src\Program.cs:line 25

### Screenshots

![image](https://user-images.githubusercontent.com/26350333/160590761-010e3abe-f658-4d41-aee8-42a21c2f47b1.png)

**Comment by albertospelta** [comment] 2022-03-29 18:51
Hi @Anaa97, thanks for reporting this! I'm closing this issue as duplicate of https://github.com/sql-bi/Bravo/issues/225

In the meantime could you please provide more details on this issue by replying to the comment https://github.com/sql-bi/Bravo/issues/225#issuecomment-1082235281 ?

**Closed by albertospelta** 2022-03-29 18:51 UTC
Labels: duplicate

**Comment by albertospelta** [comment] 2022-03-30 12:29
@Anaa97 It appears that the Microsoft Visual C++ runtime libraries are not installed on your system. We will include this component in the MSI setup to install it automatically with the next release, in the meantime you can download and install it manually from here https://aka.ms/vs/17/release/vc_redist.x64.exe

https://github.com/sql-bi/Bravo/issues/225#issuecomment-1083064111
