### ISSUE TITLE
Error HTTP/500: Internal Server Error. Error display when open an active source

### ISSUE THREAD

**Issue by Zhaidon** [sql-bi/Bravo#248] opened 2022-03-30 00:44 UTC
Provide a detailed explanation of the issue in English.
Get this error when open an active PBIX
![image](https://user-images.githubusercontent.com/94499191/160728605-244a7796-516f-46f6-aadb-2bf89eece54a.png)

-------
Error HTTP/500: Internal Server Error.
[{"Code":"HTTP/500","Message":"Internal Server Error.","TraceId":"00-cd3d36c9cf08aa43a41c0d9997e2a770-7b6c85c503312c4a-00","Details":"Object reference not set to an instance of an object."}]

**Comment by danieleperilli** [comment] 2022-03-30 05:25
Thanks for reporting this. I'm closing this issue as a duplicate of #213.

**Closed by danieleperilli** 2022-03-30 05:25 UTC

**Comment by albertospelta** [comment] 2022-03-30 09:25
Fixed in [0.9.1](https://github.com/sql-bi/Bravo/releases/tag/v0.9.1)
